--- CREATING DATABASE
CREATE DATABASE MYSQL

----HOW TO MOVE TO THE DATABASE
USE MYSQL

---DROPING DATABASE
DROP DATABASE MYSQL

---VERIFY DATABASE IS EXISTS OR NOT
IF EXISTS(SELECT 1 FROM SYS.databases WHERE NAME='MYSQL')
BEGIN
	PRINT 'EXIST'
END
ELSE
BEGIN
	PRINT 'NOT EXIST'
END


---RENAME THE DATABASE
ALTER DATABASE MYSQL MODIFY NAME=MYSQLSAMPLE


------NOTES
SYS.DATABASE IS THE BUIT IN TABLE THAT CONTAINS ALL THE DATABASE INFORMATION




