USE MYSQLSAMPLE

--CREATE TABLE
CREATE TABLE STUDENT (ID INT PRIMARY KEY,
NAME NVARCHAR(50) NOT NULL)

--CREATING SCHEMA
CREATE SCHEMA DTO

--CREATE TABLE WITH DIFFERENT SCHEMA
CREATE TABLE [DTO].[STUDENT](ID INT PRIMARY KEY,
NAME NVARCHAR(50) NOT NULL)

--VERIFY TABLE IS EXISTS OR NOT
IF EXISTS (SELECT 1 FROM SYS.tables WHERE NAME = 'STUDENT' AND schema_id IN (SELECT schema_id FROM SYS.schemas WHERE name = 'DTO'))
BEGIN
	PRINT 'TABLE ALREADY EXIST'
END
ELSE
BEGIN
	PRINT 'TABLE DOES NOT EXIST'
END
